# Generated by Django 5.1.3 on 2025-02-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_address_delete_housing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='hostel',
        ),
    ]
