# Generated by Django 5.1.3 on 2025-02-07 08:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_alter_address_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('stop_id', models.CharField(max_length=255)),
                ('stop_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorActivities',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('sport', models.CharField(max_length=254)),
            ],
        ),
    ]
