# Generated by Django 5.1.3 on 2025-02-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_busstop_outdooractivities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='outdooractivities',
            options={'managed': False},
        ),
    ]
