# Generated by Django 5.1.3 on 2025-02-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_alter_busstop_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busstop',
            table='bus_stops',
        ),
        migrations.AlterModelTable(
            name='outdooractivities',
            table='outdoor_activities',
        ),
    ]
