# Generated by Django 5.1.3 on 2025-02-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_alter_busstop_table_alter_outdooractivities_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('addr_postc', models.CharField(max_length=255)),
                ('addr_stree', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'university_buildings',
                'managed': False,
            },
        ),
    ]
