# Generated by Django 5.1.3 on 2025-02-09 09:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=25832)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
    ]
